### ISSUE TITLE
Документацию народу

### ISSUE THREAD

**Issue by radostkali** [odryfox/millet#5]
Я, как дефолтный пользователь, хочу заюзать вашу чудную либу, но не могу этого сделать без документации. прошу исправить сию незначительную оплошность. Народу нужна дока, рабочим нужна спека.

**Comment by odryfox** [comment]
Millet - кандидат для создания чат-ботов от народа.

Инструкция по использованию https://odryfox.github.io/millet/.

**Comment by radostkali** [comment]
От души!
